# Generated by Django 5.1.5 on 2025-02-27 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_company_customeruser_position_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='django_companies',
        ),
        migrations.AlterModelTable(
            name='customeruser',
            table='django_users',
        ),
        migrations.AlterModelTable(
            name='position',
            table='django_positions',
        ),
    ]
