# Generated by Django 5.1.5 on 2025-02-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_company_table_alter_customeruser_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
